name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
        with:
          args: zip -r puppies-delight-tweaks-${{ steps.tag.outputs.tag }}.zip data pack.mcmeta
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: false
          name: Release ${{ steps.tag.outputs.tag }}
          artifacts: puppies-delight-tweaks-${{ steps.tag.outputs.tag }}.zip
          artifactContentType: application/gzip

