name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
        with:
          args: zip -r puppies-delight-tweaks-${{ github.ref }}.zip data pack.mcmeta
      - uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          name: Release ${{ github.ref }}
          artifacts: puppies-delight-tweaks-${{ github.ref }}.zip
          artifactContentType: application/gzip

